export const Database =
[{"id":1,"car_model":"Seville","car_company":"Cadillac","rent_price":10000,"location":"Patna","fuel":41,"img":"images/car1.jpeg"},
{"id":2,"car_model":"Hombre","car_company":"Isuzu","rent_price":14000,"location":"Kanpur","fuel":38,"img":"images/car2.jpeg"},
{"id":3,"car_model":"Silverado","car_company":"Chevrolet","rent_price":3482,"location":"Gurgao","fuel":49,"img":"images/car3.jpeg"},
{"id":4,"car_model":"200SX","car_company":"Nissan","rent_price":14000,"location":"Banglore","fuel":12,"img":"images/car4.jpeg"},
{"id":5,"car_model":"Seville","car_company":"Cadillac","rent_price":14000,"location":"Patna","fuel":17,"img":"images/car5.jpeg"},
{"id":6,"car_model":"S10","car_company":"Chevrolet","rent_price":28470,"location":"kanpur","fuel":20,"img":"images/car6.jpeg"},
{"id":7,"car_model":"Golf","car_company":"Volks","rent_price":28470,"location":"Lucknow","fuel":18,"img":"images/car1.jpeg"},
{"id":8,"car_model":"7 Series","car_company":"BMW","rent_price":9000,"location":"Ghaziabad","fuel":23,"img":"images/car2.jpeg"},
{"id":9,"car_model":"7 Series","car_company":"BMW","rent_price":19380,"location":"Indore","fuel":30,"img":"images/car3.jpeg"},
{"id":10,"car_model":"RX-7","car_company":"Mazda","rent_price":12000,"location":"Kanpur","fuel":31,"img":"images/car1.jpeg"},
{"id":11,"car_model":"Corvette","car_company":"Chevrolet","rent_price":10000,"location":"Patna","fuel":22,"img":"images/car2.jpeg"},
{"id":12,"car_model":"Explorer","car_company":"Ford","rent_price":19282,"location":"Gurgao","fuel":26,"img":"images/car1.jpeg"},
{"id":13,"car_model":"Sprinter","car_company":"Mercedes","rent_price":13400,"location":"Gorakhpur","fuel":49,"img":"images/car2.jpeg"},
{"id":14,"car_model":"Forenza","car_company":"Suzuki","rent_price":9000,"location":"Aligarh","fuel":26,"img":"images/car1.jpeg"},
{"id":15,"car_model":"SVX","car_company":"Subaru","rent_price":12230,"location":"Dehradun","fuel":50,"img":"images/car3.jpeg"},
{"id":16,"car_model":"Cutlass ","car_company":"Oldsmobile","rent_price":12300,"location":"New Delhi","fuel":47,"img":"images/car1.jpeg"},
{"id":17,"car_model":"Monte","car_company":"Chevrolet","rent_price":20833,"location":"Lucknow","fuel":31,"img":"images/car2.jpeg"},
{"id":18,"car_model":"Mazda ","car_company":"Mazda","rent_price":23094,"location":"Kanpur","fuel":24,"img":"images/car3.jpeg"},
{"id":19,"car_model":"Trans Sport","car_company":"Pontiac","rent_price":23400,"location":"GopalGanj","fuel":15,"img":"images/car4.jpeg"},
{"id":20,"car_model":"Ranger","car_company":"Ford","rent_price":12000,"location":"Mumbai","fuel":45,"img":"images/car5.jpeg"},
{"id":21,"car_model":"Dakota","car_company":"Dodge","rent_price":12300,"location":"Jhasi","fuel":11,"img":"images/car6.jpeg"},
{"id":22,"car_model":"Jetta","car_company":"Volks","rent_price":40000,"location":"Patna","fuel":48,"img":"images/car1.jpeg"},
{"id":23,"car_model":"500SL","car_company":"Merce","rent_price":1000,"location":"Kanpur","fuel":41,"img":"images/car2.jpeg"},
{"id":24,"car_model":"GranSport","car_company":"Maserati","rent_price":4000,"location":"Kolkatta","fuel":14,"img":"images/car3.jpeg"},
{"id":25,"car_model":"IS","car_company":"Lexus","rent_price":6000,"location":"Lucknow","fuel":10,"img":"images/car4.jpeg"},
{"id":26,"car_model":"Accord","car_company":"Honda","rent_price":21000,"location":"Kanpur","fuel":45,"img":"images/car5.jpeg"},
{"id":27,"car_model":"Express","car_company":"Chevrolet","rent_price":12230,"location":"Gorakhpur","fuel":30,"img":"images/car6.jpeg"},
{"id":28,"car_model":"Touareg","car_company":"Volks","rent_price":29800,"location":"Jhasi","fuel":10,"img":"images/car1.jpeg"},
{"id":29,"car_model":"Yukon XL","car_company":"GMC","rent_price":24000,"location":"Panipat","fuel":43,"img":"images/car2.jpeg"},
{"id":30,"car_model":"Aspire","car_company":"Ford","rent_price":12000,"location":"Dehradun","fuel":43,"img":"images/car3.jpeg"}]
 